name: Python-Flask1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurando Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install -r requirements.txt
    - run: pytest

    - name: Deploy to Render
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          --data '{"serviceId": "usr-crfllg08fa8c73d87edg"}' \
          https://api.render.com/v1/services/usr-crfllg08fa8c73d87edg/deploys



